name: Barclaycard For Business
uri: https://apps.apple.com/us/app/barclaycard-for-business/id1538982647
bypasses:
- name: Hestia
- notes: Compatibility Mode <strong>must</strong> be <strong>enabled</strong> for Hestia to work