name: ila Bank
uri: https://apps.apple.com/bh/app/ila-bank/id1480238512
bypasses:
  - name: Liberty Lite (Beta)
  - name: libhooker-configurator
  - notes: Tested on odysseyra1n, iOS 14.8. Use libhooker-configurator to allow injection for only `zzzzzLiberty`