name: "Pok\xE9mon GO"
bundleId: com.nianticlabs.pokemongo
uri: https://apps.apple.com/us/app/pok%C3%A9mon-go/id1094591345
icon: https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/2e/5b/1f/2e5b1f19-b1b8-7d8f-0a0c-07e18f0f8c8f/source/512x512bb.jpg
bypasses:
- name: vnodebypass
- name: SxBypass
