name: RiyadBank Mobile
bundleId: com.riyadbank.strategic
uri: https://apps.apple.com/sa/app/riyadbank-mobile/id1445567211
icon: https://is5-ssl.mzstatic.com/image/thumb/Purple126/v4/d4/e6/2a/d4e62a91-f753-0ebf-5289-70db21ff6c54/source/512x512bb.jpg
bypasses: null
