name: Deploy manifests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip-ci')" 
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Checkout publishing branch
        uses: actions/checkout@v2
        with:
          ref: docsify
          path: ./publish
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
      -
        name: Installing build dependencies
        run: pip install -r ci/requirements.txt
      -
        name: Updating bypass table
        run: |  
          python ci/main.py
          cp README.md publish/docs/app-list.md
      -
        name: Push updated table
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docsify
          FOLDER: publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          