name: Deploy manifests

on:
  push:
    branches:
      - main

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
      -
        name: Installing build dependencies
        run: pip install -r requirements.txt
      -
        name: Setup pre-commit
        run: pre-commit install
      -
        name: Run pre-commit hooks
        run: pre-commit run -a
      -
        name: Push changed files
        uses: EndBug/add-and-commit@v7
        if: always()
        with:
          message: 'Fix files that failed pre-commit checks'
          signoff: true
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    needs: pre-commit-hooks
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
      -
        name: Installing build dependencies
        run: pip install -r ci/requirements.txt
      -
        name: Updating bypass table
        run: |
          python ci/main.py
          cp app-list.md publish/docs/app-list.md
      -
        name: Push updated table
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docsify
          FOLDER: publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
