name: Deploy manifests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: jbdetectlist/
      -
        name: Checkout publishing branch
        uses: actions/checkout@v2
        with:
          ref: publish
          path: publish/
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
      -
        name: Installing build dependencies
        run: pip install -r jbdetectlist/ci/requirements.txt
      -
        name: Updating bypass table
        run: |  
          python jbdetectlist/ci/main.py
          cp jbdetectlist/README.md publish/README.md
      -
        name: Push updated table
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: publish
          FOLDER: publish
          SSH_PRIVATE_KEY: ${{ secrets.GITHUB_TOKEN }}
          